### ISSUE TITLE
OOP Scooter Project Notes

### ISSUE THREAD

**Issue by dunnoconnor** [saeed0786/Scooter-Challenge#1]
Hi Saeed,

Good work this week.  This activity seemed to be much more useful after you started walking through it step by step.  You have some errors in your tests.  You will need to resolve the errors in your test file before you can run them.  Also, it looks like your user class is importing a person class but there is no person class.  Let me know if you need help revising.

-Michael

**Comment by saeed0786** [comment]
Thank you for the update. I will dive in to and fix the issues.
